# --- !Ups

CREATE TABLE "POSTS" ("ID" BIGINT NOT NULL AUTO_INCREMENT UNIQUE, "TITLE" VARCHAR(255) NOT NULL, "CONTENT" VARCHAR(255) NOT NULL);
INSERT INTO "POSTS" VALUES (1, 'Post #[1]', 'First post content');
INSERT INTO "POSTS" VALUES (2, 'Post #[2]', 'Second post content');
INSERT INTO "POSTS" VALUES (3, 'Post #[3]', 'Third post content');

# --- !Downs

DELETE FROM "POSTS" WHERE ID = 1;
DELETE FROM "POSTS" WHERE ID = 2;
DELETE FROM "POSTS" WHERE ID = 3;
DROP TABLE "POSTS";
